import React from 'react'
import navbar from './Navbar.css'
import global from './Global.css'
import home from './Home.css'
import about from './About.css'
import service from './Services.css'
import sign from './Signup.css'
import signin from './Signin.css'
import serviceDetails from './ServiceDetails.css'
import card from './Card.css'
import myOrders from './MyOrders.css'
import payment from './Payment.css'
import verticalNavbar from './VerticalNavbar.css'
import dashboard from './Dashboard.css'
import pendingWorks from './PendingWorks.css'
import orderReq from './OrderReq.css'
import allowance from './Allowance.css'
import adminVerticalNav from './AdminVerticalNav.css'
import adminDashboard from './AdminDashboard.css'
import booking from './Booking.css'
import employeeManagement from './EmployeeManagement.css'
import viewEmployee from './ViewEmployee.css'
import allowanceDetails from './AllowanceDetails.css'
import customerMgt from './CustomerMgt.css'
import review from './Review.css'
import reviewCheck from './ReviewCheck.css'
import method from './PaymentMethod.css'
import addEmployee from './AddEmployee.css'
import contact from './Contact.css'
import question from './Question.css'

export {navbar, global, home, about, service, sign, signin, dashboard, pendingWorks, orderReq, allowance, adminVerticalNav, adminDashboard, 
     serviceDetails, card, myOrders, payment, verticalNavbar, booking, employeeManagement, viewEmployee, allowanceDetails, customerMgt,
     review, reviewCheck, method, addEmployee, contact, question
     
     }    